version: "3.3"
   
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - './back:/usr/src/app'
      - '/app/node_modules'
    ports:
      - "8000:8000"

  front:
    stdin_open: true
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
      - './front:/app'
    ports:
      - "3000:3000"

volumes:
  back:
  front: